#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# Merlino / Caldera (EC2) - Localhost vhost certificate + Nginx CORS
# ============================================================
#
# Purpose:
# - Create (or reuse) a self-signed TLS certificate valid for DNS:localhost
# - Configure an Nginx vhost: server_name localhost; listen 443 ssl;
# - Proxy to local Caldera (default http://127.0.0.1:8888)
# - Add CORS headers and handle OPTIONS preflight for WebView2/Office Add-in
#
# This is designed for the AWS SSM port-forward use case:
# - Windows PC calls: https://localhost:8443  (port-forward -> EC2:443)
# - Merlino origin is: https://localhost:3000
# - Requests include custom header: KEY  (triggers CORS preflight)
#
# IMPORTANT:
# - This script must be run on the EC2 instance (or any Linux host running Nginx).
# - It will write:
#   - Cert: /etc/nginx/ssl-localhost/localhost.crt + localhost.key
#   - Nginx vhost: /etc/nginx/conf.d/caldera-localhost.conf
#
# Usage examples:
#   sudo bash setup-caldera-localhost-nginx-cors-and-cert.sh
#   sudo CALDERA_UPSTREAM=http://127.0.0.1:8888 MERLINO_ORIGIN=https://localhost:3000 bash setup-caldera-localhost-nginx-cors-and-cert.sh
#

CALDERA_UPSTREAM="${CALDERA_UPSTREAM:-http://127.0.0.1:8888}"
MERLINO_ORIGIN="${MERLINO_ORIGIN:-https://localhost:3000}"

SSL_DIR="/etc/nginx/ssl-localhost"
CRT_PATH="${SSL_DIR}/localhost.crt"
KEY_PATH="${SSL_DIR}/localhost.key"
CONF_PATH="/etc/nginx/conf.d/caldera-localhost.conf"
/conf.d/caldera-localhost.conf"

ALLOW_ORIGIN="${ALLOW_ORIGIN:-*}"
# If you prefer to restrict CORS instead of '*', set:
#   ALLOW_ORIGIN="$MERLINO_ORIGIN"

log() {
  echo "[INFO] $*"
}

warn() {
  echo "[WARNING] $*" >&2
}

err() {
  echo "[ERROR] $*" >&2
}

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    err "Run as root (use sudo)."
    exit 1
  fi
}

require_cmd() {
  local cmd="$1"
  if ! command -v "${cmd}" >/dev/null 2>&1; then
    err "Missing required command: ${cmd}"
    exit 1
  fi
}

ensure_packages() {
  # Best-effort: not all distros have apt/yum/dnf available.
  if command -v apt-get >/dev/null 2>&1; then
    log "Installing required packages via apt-get (nginx, openssl)..."
    apt-get update -y
    apt-get install -y nginx openssl
  elif command -v yum >/dev/null 2>&1; then
    log "Installing required packages via yum (nginx, openssl)..."
    yum install -y nginx openssl
  elif command -v dnf >/dev/null 2>&1; then
    log "Installing required packages via dnf (nginx, openssl)..."
    dnf install -y nginx openssl
  else
    warn "No supported package manager found (apt/yum/dnf). Ensure nginx and openssl are installed."
  fi
}

ensure_cert() {
  mkdir -p "${SSL_DIR}"
  chmod 700 "${SSL_DIR}"

  if [[ -f "${CRT_PATH}" && -f "${KEY_PATH}" ]]; then
    log "Certificate already exists: ${CRT_PATH}"
    return 0
  fi

  log "Generating self-signed certificate for DNS:localhost..."

  # Create cert with SAN: DNS:localhost
  # Using OpenSSL config inline to ensure SAN is present.
  local tmpconf
  tmpconf="$(mktemp)"
  cat >"${tmpconf}" <<'EOF'
[ req ]
distinguished_name = req_distinguished_name
x509_extensions = v3_req
prompt = no

[ req_distinguished_name ]
C = US
ST = State
L = City
O = Merlino
CN = localhost

[ v3_req ]
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[ alt_names ]
DNS.1 = localhost
EOF

  openssl req -x509 -nodes -newkey rsa:4096 -days 3650 \
    -keyout "${KEY_PATH}" \
    -out "${CRT_PATH}" \
    -config "${tmpconf}"

  rm -f "${tmpconf}"

  chmod 600 "${KEY_PATH}"
  chmod 644 "${CRT_PATH}"

  log "Certificate created: ${CRT_PATH}"
}

write_nginx_conf() {
  log "Writing nginx vhost config: ${CONF_PATH}"

  cat >"${CONF_PATH}" <<EOF
# Auto-generated by setup-caldera-localhost-nginx-cors-and-cert.sh
# Purpose: Serve Caldera behind https://localhost with correct CORS for Merlino.

server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate     ${CRT_PATH};
    ssl_certificate_key ${KEY_PATH};

    # Optional hardening
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    # Proxy settings
    location / {
        proxy_pass ${CALDERA_UPSTREAM};
        proxy_http_version 1.1;

        # Preserve client info
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        # CORS Headers
        add_header 'Access-Control-Allow-Origin' '${ALLOW_ORIGIN}' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS, PATCH' always;
        add_header 'Access-Control-Allow-Headers' 'Content-Type, KEY, Authorization, X-Requested-With, Accept, Origin' always;
        add_header 'Access-Control-Expose-Headers' 'Content-Length, Content-Type' always;
        add_header 'Access-Control-Max-Age' '86400' always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;

        # Handle preflight OPTIONS requests
        if (\$request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '${ALLOW_ORIGIN}' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS, PATCH' always;
            add_header 'Access-Control-Allow-Headers' 'Content-Type, KEY, Authorization, X-Requested-With, Accept, Origin' always;
            add_header 'Access-Control-Max-Age' '86400' always;
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' '0';
            return 204;
        }
    }
}
EOF
}

enable_and_reload_nginx() {
  log "Validating nginx configuration..."
  nginx -t

  if command -v systemctl >/dev/null 2>&1; then
    log "Reloading nginx via systemctl..."
    systemctl enable nginx >/dev/null 2>&1 || true
    systemctl reload nginx
  else
    warn "systemctl not found; attempting nginx -s reload"
    nginx -s reload
  fi

  log "Done. Nginx is reloaded."
}

print_validation_steps() {
  cat <<EOF

[INFO] Validation (run on Windows PC):

PowerShell preflight (OPTIONS):

  \$base = "https://localhost:8443"
  try {
    \$r = Invoke-WebRequest -Method Options -Uri "\$base/api/v2/abilities" -UseBasicParsing -TimeoutSec 20 -Headers @{
      Origin = "${MERLINO_ORIGIN}"
      "Access-Control-Request-Method" = "GET"
      "Access-Control-Request-Headers" = "KEY,Content-Type"
    }

    "StatusCode: \$(\$r.StatusCode)"
    "ACAO: " + \$r.Headers["Access-Control-Allow-Origin"]
    "ACAM: " + \$r.Headers["Access-Control-Allow-Methods"]
    "ACAH: " + \$r.Headers["Access-Control-Allow-Headers"]
  } catch {
    "ERROR: " + \$_.Exception.Message
    if (\$_.Exception.Response) { "HTTP: " + [int]\$_.Exception.Response.StatusCode }
  }

Expected:
- StatusCode 204
- ACAH includes KEY

Authenticated GET (replace KEY value as needed):

  \$base = "https://localhost:8443"
  Invoke-WebRequest -Method Get -Uri "\$base/api/v2/abilities" -UseBasicParsing -TimeoutSec 30 -Headers @{
    Origin = "${MERLINO_ORIGIN}"
    KEY = "ADMIN123"
  } | Select-Object StatusCode

Expected:
- StatusCode 200

TLS note:
- The generated certificate is self-signed. Windows/WebView2 must trust it.
- Either import the certificate (or its CA) into the Windows Trusted Root store,
  or use a corporate/internal CA to issue a localhost cert.
EOF
}

main() {
  require_root

  # Ensure commands exist; install packages if possible.
  ensure_packages
  require_cmd openssl
  require_cmd nginx

  log "Using CALDERA_UPSTREAM=${CALDERA_UPSTREAM}"
  log "Using MERLINO_ORIGIN=${MERLINO_ORIGIN}"
  log "Using ALLOW_ORIGIN=${ALLOW_ORIGIN}"

  ensure_cert
  write_nginx_conf
  enable_and_reload_nginx
  print_validation_steps
}

main "$@"
