"""
Nginx Manager for Caldera + Merlino Integration

Automatically manages Nginx reverse proxy configuration and status
to enable HTTPS + CORS communication between Merlino Excel Add-in and Caldera.
"""

import logging
import os
import subprocess
import sys
from pathlib import Path


class NginxManager:
    """Manages Nginx reverse proxy for Caldera."""

    NGINX_CONFIG_PATH = "/etc/nginx/sites-available/caldera-proxy"
    NGINX_ENABLED_PATH = "/etc/nginx/sites-enabled/caldera-proxy"
    SSL_DIR = "/etc/nginx/ssl"
    SSL_CERT = f"{SSL_DIR}/caldera.crt"
    SSL_KEY = f"{SSL_DIR}/caldera.key"

    def __init__(self, caldera_ip="192.168.124.133", caldera_port=8888):
        self.caldera_ip = caldera_ip
        self.caldera_port = caldera_port
        self.logger = logging.getLogger("nginx_manager")

    def check_nginx_installed(self):
        """Check if Nginx is installed."""
        try:
            result = subprocess.run(
                ["which", "nginx"],
                capture_output=True,
                text=True,
                check=False
            )
            return result.returncode == 0
        except Exception as e:
            self.logger.debug(f"Error checking nginx installation: {e}")
            return False

    def is_nginx_running(self):
        """Check if Nginx service is running."""
        try:
            result = subprocess.run(
                ["systemctl", "is-active", "nginx"],
                capture_output=True,
                text=True,
                check=False
            )
            return result.stdout.strip() == "active"
        except Exception as e:
            self.logger.debug(f"Error checking nginx status: {e}")
            return False

    def is_configured(self):
        """Check if Nginx is configured for Caldera proxy."""
        return (
            os.path.exists(self.NGINX_CONFIG_PATH) and
            os.path.exists(self.NGINX_ENABLED_PATH) and
            os.path.exists(self.SSL_CERT) and
            os.path.exists(self.SSL_KEY)
        )

    def install_nginx(self):
        """Install Nginx package."""
        self.logger.info("Installing Nginx...")
        try:
            subprocess.run(["apt", "update"], check=True, capture_output=True)
            subprocess.run(
                ["apt", "install", "-y", "nginx", "openssl"],
                check=True,
                capture_output=True
            )
            self.logger.info("✓ Nginx installed successfully")
            return True
        except subprocess.CalledProcessError as e:
            self.logger.error(f"Failed to install Nginx: {e}")
            return False

    def generate_ssl_certificate(self):
        """Generate self-signed SSL certificate."""
        if os.path.exists(self.SSL_CERT) and os.path.exists(self.SSL_KEY):
            self.logger.debug("SSL certificate already exists")
            return True

        self.logger.info("Generating SSL certificate (valid for 10 years)...")
        try:
            os.makedirs(self.SSL_DIR, exist_ok=True)
            subprocess.run(
                [
                    "openssl", "req", "-x509", "-nodes", "-days", "3650",
                    "-newkey", "rsa:4096",
                    "-keyout", self.SSL_KEY,
                    "-out", self.SSL_CERT,
                    "-subj", f"/C=IT/ST=State/L=City/O=X3M-AI/OU=Merlino/CN={self.caldera_ip}",
                    "-addext", f"subjectAltName=IP:{self.caldera_ip}"
                ],
                check=True,
                capture_output=True
            )
            os.chmod(self.SSL_CERT, 0o644)
            os.chmod(self.SSL_KEY, 0o600)
            self.logger.info("✓ SSL certificate generated (expires in 10 years)")
            return True
        except subprocess.CalledProcessError as e:
            self.logger.error(f"Failed to generate SSL certificate: {e}")
            return False

    def create_nginx_config(self):
        """Create Nginx configuration file."""
        config_content = f'''# Nginx Reverse Proxy Configuration for Caldera + CORS
# Auto-generated by Caldera for Merlino Excel Add-in integration

server {{
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {self.caldera_ip};
    
    ssl_certificate {self.SSL_CERT};
    ssl_certificate_key {self.SSL_KEY};
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    
    add_header 'Access-Control-Allow-Origin' '*' always;
    add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS, PATCH' always;
    add_header 'Access-Control-Allow-Headers' 'Content-Type, KEY, Authorization, X-Requested-With, Accept, Origin' always;
    add_header 'Access-Control-Expose-Headers' 'Content-Length, Content-Type' always;
    add_header 'Access-Control-Max-Age' '86400' always;
    add_header 'Access-Control-Allow-Credentials' 'true' always;
    
    if ($request_method = 'OPTIONS') {{
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS, PATCH' always;
        add_header 'Access-Control-Allow-Headers' 'Content-Type, KEY, Authorization, X-Requested-With, Accept, Origin' always;
        add_header 'Access-Control-Max-Age' '86400' always;
        add_header 'Content-Type' 'text/plain; charset=utf-8';
        add_header 'Content-Length' '0';
        return 204;
    }}
    
    location / {{
        proxy_pass http://127.0.0.1:{self.caldera_port};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
        proxy_buffering off;
        proxy_cache_bypass $http_upgrade;
        proxy_intercept_errors off;
    }}
    
    location /nginx-health {{
        access_log off;
        return 200 "Nginx proxy is running\\n";
        add_header Content-Type text/plain;
    }}
    
    access_log /var/log/nginx/caldera-access.log;
    error_log /var/log/nginx/caldera-error.log warn;
}}

server {{
    listen 80;
    listen [::]:80;
    server_name {self.caldera_ip};
    return 301 https://$host$request_uri;
}}
'''
        try:
            self.logger.info("Creating Nginx configuration...")
            with open(self.NGINX_CONFIG_PATH, 'w') as f:
                f.write(config_content)
            
            # Enable site
            if not os.path.exists(self.NGINX_ENABLED_PATH):
                os.symlink(self.NGINX_CONFIG_PATH, self.NGINX_ENABLED_PATH)
            
            # Disable default site
            default_enabled = "/etc/nginx/sites-enabled/default"
            if os.path.exists(default_enabled):
                os.remove(default_enabled)
            
            self.logger.info("✓ Nginx configuration created")
            return True
        except Exception as e:
            self.logger.error(f"Failed to create Nginx config: {e}")
            return False

    def test_nginx_config(self):
        """Test Nginx configuration for syntax errors."""
        try:
            subprocess.run(
                ["nginx", "-t"],
                check=True,
                capture_output=True,
                text=True
            )
            return True
        except subprocess.CalledProcessError as e:
            self.logger.error(f"Nginx config test failed: {e.stderr}")
            return False

    def start_nginx(self):
        """Start Nginx service."""
        try:
            subprocess.run(
                ["systemctl", "start", "nginx"],
                check=True,
                capture_output=True
            )
            subprocess.run(
                ["systemctl", "enable", "nginx"],
                check=True,
                capture_output=True
            )
            self.logger.info("✓ Nginx started successfully")
            return True
        except subprocess.CalledProcessError as e:
            self.logger.error(f"Failed to start Nginx: {e}")
            return False

    def restart_nginx(self):
        """Restart Nginx service."""
        try:
            subprocess.run(
                ["systemctl", "restart", "nginx"],
                check=True,
                capture_output=True
            )
            self.logger.info("✓ Nginx restarted successfully")
            return True
        except subprocess.CalledProcessError as e:
            self.logger.error(f"Failed to restart Nginx: {e}")
            return False

    def configure_firewall(self):
        """Configure UFW firewall if active."""
        try:
            result = subprocess.run(
                ["ufw", "status"],
                capture_output=True,
                text=True,
                check=False
            )
            if "Status: active" in result.stdout:
                self.logger.info("Configuring firewall...")
                subprocess.run(
                    ["ufw", "allow", "443/tcp"],
                    check=True,
                    capture_output=True
                )
                subprocess.run(
                    ["ufw", "allow", "80/tcp"],
                    check=True,
                    capture_output=True
                )
                subprocess.run(
                    ["ufw", "reload"],
                    check=True,
                    capture_output=True
                )
                self.logger.info("✓ Firewall configured")
        except Exception as e:
            self.logger.debug(f"Firewall configuration skipped: {e}")

    def setup_complete(self):
        """Complete setup process for Nginx proxy."""
        self.logger.info("[cyan]═══════════════════════════════════════════════[/cyan]")
        self.logger.info("[cyan]   Nginx Reverse Proxy Setup for Merlino[/cyan]")
        self.logger.info("[cyan]═══════════════════════════════════════════════[/cyan]")

        # Check if running as root
        if os.geteuid() != 0:
            self.logger.error(
                "[red]ERROR: Root privileges required for Nginx setup.[/red]"
            )
            self.logger.error(
                "[yellow]Please run Caldera with sudo: sudo python3 server.py[/yellow]"
            )
            return False

        # Step 1: Install Nginx if needed
        if not self.check_nginx_installed():
            self.logger.info("Nginx not found. Installing...")
            if not self.install_nginx():
                return False
        else:
            self.logger.debug("Nginx already installed")

        # Step 2: Generate SSL certificate
        if not self.generate_ssl_certificate():
            return False

        # Step 3: Create Nginx configuration
        if not self.create_nginx_config():
            return False

        # Step 4: Test configuration
        if not self.test_nginx_config():
            return False

        # Step 5: Configure firewall
        self.configure_firewall()

        # Step 6: Start/Restart Nginx
        if self.is_nginx_running():
            if not self.restart_nginx():
                return False
        else:
            if not self.start_nginx():
                return False

        self.logger.info("[green]✓ Nginx proxy configured successfully![/green]")
        self.logger.info("")
        self.logger.info("[cyan]Merlino Integration Info:[/cyan]")
        self.logger.info(f"  • HTTPS Endpoint: https://{self.caldera_ip}")
        self.logger.info(f"  • Proxying to: http://127.0.0.1:{self.caldera_port}")
        self.logger.info("  • CORS: Enabled")
        self.logger.info("")
        self.logger.info("[yellow]Next Steps:[/yellow]")
        self.logger.info(f"  1. Export certificate to Windows:")
        self.logger.info(f"     scp root@{self.caldera_ip}:{self.SSL_CERT} ~/caldera-cert.crt")
        self.logger.info("  2. Install certificate on Windows (Trusted Root CA)")
        self.logger.info(f"  3. Configure Merlino URL: https://{self.caldera_ip}")
        self.logger.info("[cyan]═══════════════════════════════════════════════[/cyan]")
        return True

    def ensure_running(self):
        """Ensure Nginx is configured and running. Called at Caldera startup."""
        # Quick check: if already configured and running, do nothing
        if self.is_configured() and self.is_nginx_running():
            self.logger.debug("Nginx proxy already configured and running")
            return True

        # Need setup
        if not self.is_configured():
            self.logger.info("[yellow]Nginx proxy not configured. Setting up...[/yellow]")
            return self.setup_complete()
        
        # Configured but not running - just start it
        if not self.is_nginx_running():
            self.logger.info("[yellow]Nginx proxy configured but not running. Starting...[/yellow]")
            return self.start_nginx()

        return True
